print("Enter the first digit")
x = input()
print("Enter the second digit")
y = input()
if x > y: print(x, "is bigger then", y)
if y > x: print(y, "is bigger then", x)
if y == x: print(y, "and", x, "are equal")